on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world!!!"
      - name: Add Reviewers to Pull Request
        uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ secrets.REVIEW_TOKEN }}
          team_reviewers: reiviews-test-team