on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
      - run: |
          echo "all-labels is $all-labels"
          echo "new-labels is $new-labels"
        env:
          all-labels: ${{ steps.label-the-PR.outputs.all-labels }}
          new-labels: ${{ steps.label-the-PR.outputs.new-labels }}