on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: KeisukeYamashita/attach-labels@v1
        with:
          labels: approve